// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Banshee.Plugins.Lyrics {
    
    
    public partial class LyricsHeader {
        
        private Gtk.HBox hbox1;
        
        private Gtk.VBox vbox1;
        
        private Gtk.Image imgArtist;
        
        private Gtk.VBox vbox3;
        
        private Gtk.Label lblTitle;
        
        private Gtk.Label lblAlbum_Artist;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Banshee.Plugins.Lyrics.LyricsHeader
            Stetic.BinContainer.Attach(this);
            this.Name = "Banshee.Plugins.Lyrics.LyricsHeader";
            // Container child Banshee.Plugins.Lyrics.LyricsHeader.Gtk.Container+ContainerChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 9;
            this.hbox1.BorderWidth = ((uint)(6));
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            this.vbox1.BorderWidth = ((uint)(3));
            // Container child vbox1.Gtk.Box+BoxChild
            this.imgArtist = new Gtk.Image();
            this.imgArtist.Name = "imgArtist";
            this.vbox1.Add(this.imgArtist);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.imgArtist]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            this.hbox1.Add(this.vbox1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = -11;
            // Container child vbox3.Gtk.Box+BoxChild
            this.lblTitle = new Gtk.Label();
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Xalign = 0F;
            this.lblTitle.LabelProp = Mono.Unix.Catalog.GetString("fff");
            this.lblTitle.UseMarkup = true;
            this.vbox3.Add(this.lblTitle);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox3[this.lblTitle]));
            w3.Position = 0;
            w3.Padding = ((uint)(5));
            // Container child vbox3.Gtk.Box+BoxChild
            this.lblAlbum_Artist = new Gtk.Label();
            this.lblAlbum_Artist.Name = "lblAlbum_Artist";
            this.lblAlbum_Artist.Xalign = 0F;
            this.lblAlbum_Artist.LabelProp = Mono.Unix.Catalog.GetString("ffffff");
            this.lblAlbum_Artist.UseMarkup = true;
            this.vbox3.Add(this.lblAlbum_Artist);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox3[this.lblAlbum_Artist]));
            w4.Position = 1;
            w4.Padding = ((uint)(6));
            this.hbox1.Add(this.vbox3);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
            w5.Position = 1;
            this.Add(this.hbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
