// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Banshee.Plugins.Lyrics {
    
    
    public partial class LyricsWindow {
        
        private Gtk.VBox vbox2;
        
        private Gtk.VBox vbox1;
        
        private Banshee.Plugins.Lyrics.LyricsHeader lyricsheader;
        
        private Banshee.Plugins.Lyrics.LyricsBrowser lyricsBrowser;
        
        private Gtk.HButtonBox dialog1_ActionArea1;
        
        private Gtk.Button buttonClose;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Banshee.Plugins.Lyrics.LyricsWindow
            this.Name = "Banshee.Plugins.Lyrics.LyricsWindow";
            this.Title = Mono.Unix.Catalog.GetString("Banshee Lyrics Plugin");
            this.Icon = Stetic.IconLoader.LoadIcon(this, "banshee", Gtk.IconSize.Menu, 16);
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Resizable = false;
            this.AllowGrow = false;
            this.AllowShrink = true;
            this.DefaultWidth = 400;
            this.DefaultHeight = 450;
            // Container child Banshee.Plugins.Lyrics.LyricsWindow.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 3;
            this.vbox2.BorderWidth = ((uint)(3));
            // Container child vbox2.Gtk.Box+BoxChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            // Container child vbox1.Gtk.Box+BoxChild
            this.lyricsheader = new Banshee.Plugins.Lyrics.LyricsHeader();
            this.lyricsheader.Events = ((Gdk.EventMask)(256));
            this.lyricsheader.Name = "lyricsheader";
            this.vbox1.Add(this.lyricsheader);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.lyricsheader]));
            w1.Position = 0;
            w1.Expand = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.lyricsBrowser = new Banshee.Plugins.Lyrics.LyricsBrowser();
            this.lyricsBrowser.Events = ((Gdk.EventMask)(256));
            this.lyricsBrowser.Name = "lyricsBrowser";
            this.vbox1.Add(this.lyricsBrowser);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.lyricsBrowser]));
            w2.Position = 1;
            this.vbox2.Add(this.vbox1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.vbox1]));
            w3.Position = 0;
            // Container child vbox2.Gtk.Box+BoxChild
            this.dialog1_ActionArea1 = new Gtk.HButtonBox();
            this.dialog1_ActionArea1.Name = "dialog1_ActionArea1";
            this.dialog1_ActionArea1.Spacing = 6;
            this.dialog1_ActionArea1.BorderWidth = ((uint)(5));
            this.dialog1_ActionArea1.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea1.Gtk.ButtonBox+ButtonBoxChild
            this.buttonClose = new Gtk.Button();
            this.buttonClose.CanDefault = true;
            this.buttonClose.CanFocus = true;
            this.buttonClose.Name = "buttonClose";
            this.buttonClose.UseStock = true;
            this.buttonClose.UseUnderline = true;
            this.buttonClose.Label = "gtk-close";
            this.dialog1_ActionArea1.Add(this.buttonClose);
            Gtk.ButtonBox.ButtonBoxChild w4 = ((Gtk.ButtonBox.ButtonBoxChild)(this.dialog1_ActionArea1[this.buttonClose]));
            w4.Expand = false;
            w4.Fill = false;
            this.vbox2.Add(this.dialog1_ActionArea1);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox2[this.dialog1_ActionArea1]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
