// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Banshee.Plugins.Lyrics {
    
    
    public partial class LyricsBrowser {
        
        private Gtk.Frame frame1;
        
        private Gtk.VBox vbox2;
        
        private Gtk.ScrolledWindow lyricsScrollPane;
        
        private Gtk.HButtonBox dialog1_ActionArea;
        
        private Gtk.Button buttonSave;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Banshee.Plugins.Lyrics.LyricsBrowser
            Stetic.BinContainer.Attach(this);
            this.Name = "Banshee.Plugins.Lyrics.LyricsBrowser";
            // Container child Banshee.Plugins.Lyrics.LyricsBrowser.Gtk.Container+ContainerChild
            this.frame1 = new Gtk.Frame();
            this.frame1.CanFocus = true;
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(4));
            this.frame1.BorderWidth = ((uint)(7));
            // Container child frame1.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 4;
            this.vbox2.BorderWidth = ((uint)(6));
            // Container child vbox2.Gtk.Box+BoxChild
            this.lyricsScrollPane = new Gtk.ScrolledWindow();
            this.lyricsScrollPane.CanFocus = true;
            this.lyricsScrollPane.Name = "lyricsScrollPane";
            this.lyricsScrollPane.HscrollbarPolicy = ((Gtk.PolicyType)(2));
            this.lyricsScrollPane.ShadowType = ((Gtk.ShadowType)(1));
            this.vbox2.Add(this.lyricsScrollPane);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox2[this.lyricsScrollPane]));
            w1.Position = 0;
            // Container child vbox2.Gtk.Box+BoxChild
            this.dialog1_ActionArea = new Gtk.HButtonBox();
            this.dialog1_ActionArea.Name = "dialog1_ActionArea";
            this.dialog1_ActionArea.Spacing = 2;
            this.dialog1_ActionArea.BorderWidth = ((uint)(2));
            this.dialog1_ActionArea.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonSave = new Gtk.Button();
            this.buttonSave.CanDefault = true;
            this.buttonSave.CanFocus = true;
            this.buttonSave.Name = "buttonSave";
            this.buttonSave.UseStock = true;
            this.buttonSave.UseUnderline = true;
            this.buttonSave.Label = "gtk-save";
            this.dialog1_ActionArea.Add(this.buttonSave);
            Gtk.ButtonBox.ButtonBoxChild w2 = ((Gtk.ButtonBox.ButtonBoxChild)(this.dialog1_ActionArea[this.buttonSave]));
            w2.Expand = false;
            w2.Fill = false;
            this.vbox2.Add(this.dialog1_ActionArea);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.dialog1_ActionArea]));
            w3.Position = 1;
            w3.Expand = false;
            w3.Fill = false;
            this.frame1.Add(this.vbox2);
            this.Add(this.frame1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
