
// This file has been generated by the GUI designer. Do not modify.
namespace Banshee.Ampache
{
	public partial class AmpacheView
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox LoginArea;

		private global::Gtk.Table table1;

		private global::Gtk.Entry entPassword;

		private global::Gtk.Entry entUrl;

		private global::Gtk.Entry entUser;

		private global::Gtk.Label lblPassword;

		private global::Gtk.Label lblUrl;

		private global::Gtk.Label lblUser;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Button btnConnect;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Frame frame2;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView ndvArtists;

		private global::Gtk.Label lblArtist;

		private global::Gtk.Frame frame3;

		private global::Gtk.Alignment GtkAlignment1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.NodeView ndvAlbums;

		private global::Gtk.Label lblAlbums;

		private global::Gtk.Frame frame4;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow2;

		private global::Gtk.NodeView ndvPlaylists;

		private global::Gtk.Label lblPlaylists;

		private global::Gtk.ScrolledWindow GtkScrolledWindow3;

		private global::Gtk.NodeView ndvSongs;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Banshee.Ampache.AmpacheView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Banshee.Ampache.AmpacheView";
			// Container child Banshee.Ampache.AmpacheView.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.LoginArea = new global::Gtk.HBox ();
			this.LoginArea.Name = "LoginArea";
			this.LoginArea.Spacing = 6;
			// Container child LoginArea.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.entPassword = new global::Gtk.Entry ();
			this.entPassword.CanFocus = true;
			this.entPassword.Name = "entPassword";
			this.entPassword.IsEditable = true;
			this.entPassword.Visibility = false;
			this.entPassword.InvisibleChar = '●';
			this.table1.Add (this.entPassword);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.entPassword]));
			w1.TopAttach = ((uint)(2));
			w1.BottomAttach = ((uint)(3));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entUrl = new global::Gtk.Entry ();
			this.entUrl.CanFocus = true;
			this.entUrl.Name = "entUrl";
			this.entUrl.IsEditable = true;
			this.entUrl.InvisibleChar = '●';
			this.table1.Add (this.entUrl);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.entUrl]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entUser = new global::Gtk.Entry ();
			this.entUser.CanFocus = true;
			this.entUser.Name = "entUser";
			this.entUser.IsEditable = true;
			this.entUser.InvisibleChar = '●';
			this.table1.Add (this.entUser);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.entUser]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblPassword = new global::Gtk.Label ();
			this.lblPassword.Name = "lblPassword";
			this.lblPassword.LabelProp = global::Mono.Unix.Catalog.GetString ("Password:");
			this.lblPassword.Justify = ((global::Gtk.Justification)(1));
			this.lblPassword.SingleLineMode = true;
			this.table1.Add (this.lblPassword);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.lblPassword]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblUrl = new global::Gtk.Label ();
			this.lblUrl.Name = "lblUrl";
			this.lblUrl.LabelProp = global::Mono.Unix.Catalog.GetString ("Ampache Server Name:");
			this.lblUrl.Justify = ((global::Gtk.Justification)(1));
			this.lblUrl.SingleLineMode = true;
			this.table1.Add (this.lblUrl);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.lblUrl]));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblUser = new global::Gtk.Label ();
			this.lblUser.Name = "lblUser";
			this.lblUser.LabelProp = global::Mono.Unix.Catalog.GetString ("User Name:");
			this.lblUser.Justify = ((global::Gtk.Justification)(1));
			this.lblUser.SingleLineMode = true;
			this.table1.Add (this.lblUser);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.lblUser]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			this.LoginArea.Add (this.table1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.LoginArea[this.table1]));
			w7.Position = 0;
			// Container child LoginArea.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.btnConnect = new global::Gtk.Button ();
			this.btnConnect.CanFocus = true;
			this.btnConnect.Name = "btnConnect";
			this.btnConnect.UseUnderline = true;
			this.btnConnect.Label = global::Mono.Unix.Catalog.GetString ("Connect");
			this.vbox5.Add (this.btnConnect);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.btnConnect]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			this.LoginArea.Add (this.vbox5);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.LoginArea[this.vbox5]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox1.Add (this.LoginArea);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.LoginArea]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ndvArtists = new global::Gtk.NodeView ();
			this.ndvArtists.CanFocus = true;
			this.ndvArtists.Name = "ndvArtists";
			this.ndvArtists.SearchColumn = 0;
			this.GtkScrolledWindow.Add (this.ndvArtists);
			this.GtkAlignment.Add (this.GtkScrolledWindow);
			this.frame2.Add (this.GtkAlignment);
			this.lblArtist = new global::Gtk.Label ();
			this.lblArtist.Name = "lblArtist";
			this.lblArtist.LabelProp = global::Mono.Unix.Catalog.GetString ("Artists");
			this.lblArtist.UseMarkup = true;
			this.frame2.LabelWidget = this.lblArtist;
			this.hbox3.Add (this.frame2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.frame2]));
			w14.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.ndvAlbums = new global::Gtk.NodeView ();
			this.ndvAlbums.CanFocus = true;
			this.ndvAlbums.Name = "ndvAlbums";
			this.GtkScrolledWindow1.Add (this.ndvAlbums);
			this.GtkAlignment1.Add (this.GtkScrolledWindow1);
			this.frame3.Add (this.GtkAlignment1);
			this.lblAlbums = new global::Gtk.Label ();
			this.lblAlbums.Name = "lblAlbums";
			this.lblAlbums.LabelProp = global::Mono.Unix.Catalog.GetString ("Albums");
			this.lblAlbums.UseMarkup = true;
			this.frame3.LabelWidget = this.lblAlbums;
			this.hbox3.Add (this.frame3);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.frame3]));
			w18.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.ndvPlaylists = new global::Gtk.NodeView ();
			this.ndvPlaylists.CanFocus = true;
			this.ndvPlaylists.Name = "ndvPlaylists";
			this.GtkScrolledWindow2.Add (this.ndvPlaylists);
			this.GtkAlignment2.Add (this.GtkScrolledWindow2);
			this.frame4.Add (this.GtkAlignment2);
			this.lblPlaylists = new global::Gtk.Label ();
			this.lblPlaylists.Name = "lblPlaylists";
			this.lblPlaylists.LabelProp = global::Mono.Unix.Catalog.GetString ("Playlists");
			this.lblPlaylists.UseMarkup = true;
			this.frame4.LabelWidget = this.lblPlaylists;
			this.hbox3.Add (this.frame4);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.frame4]));
			w22.Position = 2;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w23.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.ndvSongs = new global::Gtk.NodeView ();
			this.ndvSongs.CanFocus = true;
			this.ndvSongs.Name = "ndvSongs";
			this.ndvSongs.SearchColumn = 0;
			this.GtkScrolledWindow3.Add (this.ndvSongs);
			this.vbox1.Add (this.GtkScrolledWindow3);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow3]));
			w25.Position = 2;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.btnConnect.Clicked += new global::System.EventHandler (this.btnConnect_OnClicked);
		}
	}
}
