
// This file has been generated by the GUI designer. Do not modify.
namespace Banshee.Ampache
{
	public partial class AmpacheView
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox LoginArea;

		private global::Gtk.Label lblConfigure;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Button btnConnect;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Frame frame2;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView ndvArtists;

		private global::Gtk.Label lblArtist;

		private global::Gtk.Frame frame3;

		private global::Gtk.Alignment GtkAlignment1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.NodeView ndvAlbums;

		private global::Gtk.Label lblAlbums;

		private global::Gtk.Frame frame4;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow2;

		private global::Gtk.NodeView ndvPlaylists;

		private global::Gtk.Label lblPlaylists;

		private global::Gtk.ScrolledWindow GtkScrolledWindow3;

		private global::Gtk.NodeView ndvSongs;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Banshee.Ampache.AmpacheView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Banshee.Ampache.AmpacheView";
			// Container child Banshee.Ampache.AmpacheView.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.LoginArea = new global::Gtk.HBox ();
			this.LoginArea.Name = "LoginArea";
			this.LoginArea.Spacing = 6;
			// Container child LoginArea.Gtk.Box+BoxChild
			this.lblConfigure = new global::Gtk.Label ();
			this.lblConfigure.Name = "lblConfigure";
			this.lblConfigure.LabelProp = global::Mono.Addins.AddinManager.CurrentLocalizer.GetString ("Please configure the Ampache extension, Edit > Perferences");
			this.LoginArea.Add (this.lblConfigure);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.LoginArea[this.lblConfigure]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child LoginArea.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.btnConnect = new global::Gtk.Button ();
			this.btnConnect.CanFocus = true;
			this.btnConnect.Name = "btnConnect";
			this.btnConnect.UseUnderline = true;
			this.btnConnect.Label = global::Mono.Addins.AddinManager.CurrentLocalizer.GetString ("Connect");
			this.vbox5.Add (this.btnConnect);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.btnConnect]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			this.LoginArea.Add (this.vbox5);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.LoginArea[this.vbox5]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox1.Add (this.LoginArea);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.LoginArea]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ndvArtists = new global::Gtk.NodeView ();
			this.ndvArtists.CanFocus = true;
			this.ndvArtists.Name = "ndvArtists";
			this.ndvArtists.SearchColumn = 0;
			this.GtkScrolledWindow.Add (this.ndvArtists);
			this.GtkAlignment.Add (this.GtkScrolledWindow);
			this.frame2.Add (this.GtkAlignment);
			this.lblArtist = new global::Gtk.Label ();
			this.lblArtist.Name = "lblArtist";
			this.lblArtist.LabelProp = global::Mono.Addins.AddinManager.CurrentLocalizer.GetString ("Artists");
			this.lblArtist.UseMarkup = true;
			this.frame2.LabelWidget = this.lblArtist;
			this.hbox3.Add (this.frame2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.frame2]));
			w8.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.ndvAlbums = new global::Gtk.NodeView ();
			this.ndvAlbums.CanFocus = true;
			this.ndvAlbums.Name = "ndvAlbums";
			this.GtkScrolledWindow1.Add (this.ndvAlbums);
			this.GtkAlignment1.Add (this.GtkScrolledWindow1);
			this.frame3.Add (this.GtkAlignment1);
			this.lblAlbums = new global::Gtk.Label ();
			this.lblAlbums.Name = "lblAlbums";
			this.lblAlbums.LabelProp = global::Mono.Addins.AddinManager.CurrentLocalizer.GetString ("Albums");
			this.lblAlbums.UseMarkup = true;
			this.frame3.LabelWidget = this.lblAlbums;
			this.hbox3.Add (this.frame3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.frame3]));
			w12.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.ndvPlaylists = new global::Gtk.NodeView ();
			this.ndvPlaylists.CanFocus = true;
			this.ndvPlaylists.Name = "ndvPlaylists";
			this.GtkScrolledWindow2.Add (this.ndvPlaylists);
			this.GtkAlignment2.Add (this.GtkScrolledWindow2);
			this.frame4.Add (this.GtkAlignment2);
			this.lblPlaylists = new global::Gtk.Label ();
			this.lblPlaylists.Name = "lblPlaylists";
			this.lblPlaylists.LabelProp = global::Mono.Addins.AddinManager.CurrentLocalizer.GetString ("Playlists");
			this.lblPlaylists.UseMarkup = true;
			this.frame4.LabelWidget = this.lblPlaylists;
			this.hbox3.Add (this.frame4);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.frame4]));
			w16.Position = 2;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w17.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.ndvSongs = new global::Gtk.NodeView ();
			this.ndvSongs.CanFocus = true;
			this.ndvSongs.Name = "ndvSongs";
			this.ndvSongs.SearchColumn = 0;
			this.GtkScrolledWindow3.Add (this.ndvSongs);
			this.vbox1.Add (this.GtkScrolledWindow3);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow3]));
			w19.Position = 2;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.btnConnect.Clicked += new global::System.EventHandler (this.btnConnect_OnClicked);
		}
	}
}
