// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace OpenVP.GtkGui {
    
    
    public partial class BrowsableEditor {
        
        private Gtk.VBox vbox2;
        
        private Gtk.ScrolledWindow SheetPane;
        
        private Gtk.HButtonBox hbuttonbox2;
        
        private Gtk.Button RevertButton;
        
        private Gtk.Button ApplyButton;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget OpenVP.GtkGui.BrowsableEditor
            Stetic.BinContainer.Attach(this);
            this.Name = "OpenVP.GtkGui.BrowsableEditor";
            // Container child OpenVP.GtkGui.BrowsableEditor.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.SheetPane = new Gtk.ScrolledWindow();
            this.SheetPane.CanFocus = true;
            this.SheetPane.Name = "SheetPane";
            this.vbox2.Add(this.SheetPane);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox2[this.SheetPane]));
            w1.Position = 0;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbuttonbox2 = new Gtk.HButtonBox();
            this.hbuttonbox2.Name = "hbuttonbox2";
            this.hbuttonbox2.Homogeneous = true;
            this.hbuttonbox2.Spacing = 6;
            this.hbuttonbox2.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.RevertButton = new Gtk.Button();
            this.RevertButton.Sensitive = false;
            this.RevertButton.CanFocus = true;
            this.RevertButton.Name = "RevertButton";
            this.RevertButton.UseStock = true;
            this.RevertButton.UseUnderline = true;
            this.RevertButton.Label = "gtk-revert-to-saved";
            this.hbuttonbox2.Add(this.RevertButton);
            Gtk.ButtonBox.ButtonBoxChild w2 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.RevertButton]));
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.ApplyButton = new Gtk.Button();
            this.ApplyButton.Sensitive = false;
            this.ApplyButton.CanFocus = true;
            this.ApplyButton.Name = "ApplyButton";
            this.ApplyButton.UseStock = true;
            this.ApplyButton.UseUnderline = true;
            this.ApplyButton.Label = "gtk-apply";
            this.hbuttonbox2.Add(this.ApplyButton);
            Gtk.ButtonBox.ButtonBoxChild w3 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.ApplyButton]));
            w3.Position = 1;
            w3.Expand = false;
            w3.Fill = false;
            this.vbox2.Add(this.hbuttonbox2);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbuttonbox2]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.RevertButton.Clicked += new System.EventHandler(this.OnRevertButtonClicked);
            this.ApplyButton.Clicked += new System.EventHandler(this.OnApplyButtonClicked);
        }
    }
}
