// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Banshee.Magnatune {


    public partial class Configuration {

        private Gtk.HBox hbox2;

        private Gtk.Label label3;

        private Gtk.Entry username;

        private Gtk.HBox hbox1;

        private Gtk.Label label2;

        private Gtk.Entry password;

        private Gtk.HBox hbox3;

        private Gtk.Label label1;

        private Gtk.ComboBox membershipType;

        private Gtk.Button buttonCancel;

        private Gtk.Button buttonOk;

        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Magnatune.Configuration
            this.Name = "Magnatune.Configuration";
            this.Title = Mono.Unix.Catalog.GetString("Magnatune Configuration");
            this.Icon = Gdk.Pixbuf.LoadFromResource("simple_icon.png");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.HasSeparator = false;
            // Internal child Magnatune.Configuration.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.Spacing = 5;
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Username");
            this.hbox2.Add(this.label3);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox2[this.label3]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.username = new Gtk.Entry();
            this.username.CanFocus = true;
            this.username.Name = "username";
            this.username.IsEditable = true;
            this.username.InvisibleChar = '\u25cf';
            this.hbox2.Add(this.username);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox2[this.username]));
            w3.Position = 1;
            w1.Add(this.hbox2);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(w1[this.hbox2]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Password");
            this.hbox1.Add(this.label2);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox1[this.label2]));
            w5.Position = 0;
            w5.Expand = false;
            w5.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.password = new Gtk.Entry();
            this.password.CanFocus = true;
            this.password.Name = "password";
            this.password.IsEditable = true;
            this.password.Visibility = false;
            this.password.InvisibleChar = '\u25cf';
            this.hbox1.Add(this.password);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox1[this.password]));
            w6.Position = 1;
            w1.Add(this.hbox1);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(w1[this.hbox1]));
            w7.Position = 1;
            w7.Expand = false;
            w7.Fill = false;
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Membership Type");
            this.hbox3.Add(this.label1);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox3[this.label1]));
            w8.Position = 0;
            w8.Expand = false;
            w8.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.membershipType = Gtk.ComboBox.NewText();
            this.membershipType.AppendText(Mono.Unix.Catalog.GetString("None"));
            this.membershipType.AppendText(Mono.Unix.Catalog.GetString("Streaming"));
            this.membershipType.AppendText(Mono.Unix.Catalog.GetString("Download"));
            this.membershipType.Name = "membershipType";
            this.membershipType.Active = 0;
            this.hbox3.Add(this.membershipType);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox3[this.membershipType]));
            w9.Position = 1;
            w9.Expand = false;
            w9.Fill = false;
            w1.Add(this.hbox3);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(w1[this.hbox3]));
            w10.Position = 2;
            w10.Expand = false;
            w10.Fill = false;
            // Internal child Magnatune.Configuration.ActionArea
            Gtk.HButtonBox w11 = this.ActionArea;
            w11.Name = "dialog1_ActionArea";
            w11.Spacing = 6;
            w11.BorderWidth = ((uint)(5));
            w11.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.buttonCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w12 = ((Gtk.ButtonBox.ButtonBoxChild)(w11[this.buttonCancel]));
            w12.Expand = false;
            w12.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w13 = ((Gtk.ButtonBox.ButtonBoxChild)(w11[this.buttonOk]));
            w13.Position = 1;
            w13.Expand = false;
            w13.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 176;
            this.Show();
            this.buttonCancel.Pressed += new System.EventHandler(this.OnButtonCancelPressed);
            this.buttonOk.Pressed += new System.EventHandler(this.OnButtonOkPressed);
        }
    }
}
