env = Environment()
conf = Configure(env)
if not conf.CheckCHeader('lirc/lirc_client.h'):
	print "liblircclient-dev must be installed!"
	Exit(1)
env = conf.Finish()

env.Clean('#', 'config.log')

SConscript('src/SConscript', variant_dir='bin/Debug', duplicate=0)
